export const GFR_FO_17_CELLS = {
  contratista: "C4",
  tipoDocumento: "G4",
  documentoContratista: "H4",
  numeroContrato: "C6",
  dependenciaContratante: "G6",
  nombreSupervisor: "C8",
  documentoSupervisor: "H8",
  objeto: "B10",
  plazoMeses: "B15",
  fechaActaInicio: "C15",
  fechaFinal: "D15",
  concepto: "E15",
  rubro: "F15",
  cdp: "G15",
  valorCdp: "H15",
  rpc: "I15",
  valorRpc: "J15",
  valorInicialContrato: "K15",
  totalRecursosComprometidos: "K23",
  cuentaNumero: "E27",
  periodoDesde: "C29",
  periodoHasta: "G29",
  valorPagoNumeros: "C31",
  valorPagoLetras: "C32",
  planillaSalud: "F36",
  planillaPension: "G36",
  planillaArl: "H36",
  disponibilidadActual: "B44",
  compromisoActual: "D44",
  rubroActual: "F44",
  conceptoActual: "G44",
  centroCostoActual: "H44",
  valorActual: "J44",
  cuentaActualTotal: "J50",
  historialTotalHonorarios: "F59",
  historialTotalGastos: "G59",
  historialTotalIva: "H59",
  valorContractual: "F60",
  valorContractualGastos: "G60",
  valorContractualIva: "H60",
  saldoContractualHonorarios: "F61",
  saldoContractualGastos: "G61",
  saldoContractualIva: "H61",
  declaracion383Si: "D67",
  declaracion383No: "F67",
  declaracionRutSi: "D71",
  declaracionRutNo: "F71",
  porcentajeEjecucionFinanciera: "E76",
  porcentajeEjecucionFisica: "J76",
  actividadStartRow: 80,
  documentoContratistaFirma: "H123",
  tipoInforme: "E129",
  documentoSupervisorFirma: "B136",
  fechaExpedicion: "G135",
} as const;

export const GFR_FO_17_HISTORIAL_START_ROW = 53;
export const GFR_FO_17_HISTORIAL_MAX_ROWS = 6;

export const GFR_FO_17_SIGNATURE_ANCHORS = {
  contratista: {
    tl: { col: 1.0, row: 122.9 },
    ext: { width: 220, height: 40 },
  },
  supervisor: {
    tl: { col: 1.0, row: 134.9 },
    ext: { width: 220, height: 40 },
  },
} as const;
