export const GFR_FO_11_CELLS = {
  nombre: "C3",
  documento: "Q3",
  numeroContrato: "G4",
  diaFirma: "E29",
  mesFirma: "G29",
  anioFirma: "M29",
  documentoFirma: "E35",
  uvtAnioAnterior: "AB1",
  uvtAnioActual: "AC1",
  ingresosAnioAnteriorLabel: "C8",
  ingresosAnioAnteriorValor: "E8",
  ingresosAnioActualLabel: "C9",
  ingresosAnioActualValor: "E9",
  contratosServiciosAnioAnteriorLabel: "C17",
  contratosServiciosAnioAnteriorValor: "E17",
  contratosServiciosAnioActualLabel: "C18",
  contratosServiciosAnioActualValor: "E18",
  contratosEstadoAnioAnteriorLabel: "C20",
  contratosEstadoAnioAnteriorValor: "E20",
  contratosEstadoAnioActualLabel: "C21",
  contratosEstadoAnioActualValor: "E21",
  consignacionesAnioAnteriorLabel: "C23",
  consignacionesAnioAnteriorValor: "E23",
  consignacionesAnioActualLabel: "C24",
  consignacionesAnioActualValor: "E24",
} as const;

export const GFR_FO_11_SI_NO_ROWS = {
  ingresosAnioAnterior: 8,
  ingresosAnioActual: 9,
  multiplesEstablecimientos: 11,
  establecimientoDesarrolloActividad: 13,
  usuarioAduanero: 15,
  contratosServiciosAnioAnterior: 17,
  contratosServiciosAnioActual: 18,
  contratosEstadoAnioAnterior: 20,
  contratosEstadoAnioActual: 21,
  consignacionesAnioAnterior: 23,
  consignacionesAnioActual: 24,
  regimenSimple: 26,
} as const;
